### ISSUE TITLE
This is a bug?

### ISSUE THREAD

**Issue by nim** [bazzilic/PaillierExt#15]
static void Perfomance()
        {
            Paillier algorithm = new PaillierManaged
            {
                Padding = PaillierPaddingMode.BigIntegerPadding,
                KeySize = 512
            };

            var x = algorithm.EncryptData(new BigInteger(0).ToByteArray());
            var y = algorithm.EncryptData(new BigInteger(1).ToByteArray());

            var res = (byte[]) x.Clone();

            for (var i = 0; i < 1000; ++i)
            {
                res = algorithm.Addition(res, y);

                // res size here 128 must be 130
            }

            var z_dec_bytes = algorithm.DecryptData(res);
            var z_dec = new BigInteger(z_dec_bytes);

            Console.WriteLine(z_dec);
        }

**Comment by bazzilic** [comment]
What versions are the DLLs you use?

**Comment by nim** [comment]
Download today from this. 
0.10.0.10
![default](https://user-images.githubusercontent.com/41398/34360022-07194db4-ea6e-11e7-86b4-e843e541bd93.png)

**Comment by bazzilic** [comment]
Yes, looks like a bug. Will look into that.

**Comment by nim** [comment]
Are you planning to do more operations? Such as XOR MUL Division and others. And one more question. PailllierExt-Homomorphism.dll has open source ?

**Comment by bazzilic** [comment]
Paillier cryptosystem only supports homomorphic addition and multiplication by a plaintext constant.
Here's the source for Homomorphism https://github.com/bazzilic/PaillierExt-Homomorphism

**Comment by nim** [comment]
Read this:
1. https://community.embarcadero.com/blogs/entry/a-math-primer-for-gentrys-fully-homomorphic-encryption-38577
2. https://crypto.stackexchange.com/tags/paillier/hot

**Comment by bazzilic** [comment]
Gentry’s is a different cryptosystem. Paillier supports addition between ciphertexts and multiplication (or division) between a ciphertext and a plaintext integer.

**Comment by bazzilic** [comment]
Fixed in the latest commit.

**Comment by nim** [comment]
Thanks.

> Paillier supports addition between ciphertexts and multiplication

NAND(x, y) = (1 — xy) right?

**Comment by nim** [comment]
I have one more question. Why it not work this:

        static void Perfomance()
        {
            Paillier algorithm = new PaillierManaged
            {
                Padding = PaillierPaddingMode.BigIntegerPadding,
                KeySize = 512
            };

            var x = new BigInteger(algorithm.EncryptData(new BigInteger(0).ToByteArray()));
            var y = new BigInteger(algorithm.EncryptData(new BigInteger(1).ToByteArray()));

            var sw = Stopwatch.StartNew();

            for (var i = 0; i < 100; ++i)
            {
                x += y;
            }

            Console.WriteLine(sw.ElapsedMilliseconds);

            var z_dec_bytes = algorithm.DecryptData(x.ToByteArray());
            var z_dec = new BigInteger(z_dec_bytes);

            Console.WriteLine(z_dec);
        }

Why your addition required p_NSquare? How i can take this to another side with Key ??

**Comment by bazzilic** [comment]
> NAND(x, y) = (1 — xy) right?
Not sure what this is about. What is NAND?

Homomorphic addition of ciphertexts is not done by simply adding them, there is a more complex operation that _results_ in an encrypted sum. Actually, in Paillier, homomorphic addition of ciphertexts A and B is done as A * B mod N_squared, IIRC.

N_squared is part of the public key, so it is safe to share it with any party (at least, from the point of view of confidentiality).

You might want to read wikipedia articles about public key cryptography and Paillier cryptosystem.

**Comment by nim** [comment]
Ok, Thanks. So multiplication (a * b) = a adds b-times ?

> Not sure what this is about. What is NAND?

https://en.wikipedia.org/wiki/NAND_gate

**Comment by bazzilic** [comment]
If you want to multiply `a` by `b`, and you want to keep `b` encrypted (i.e., you do not want to reveal what `b` is), then you can't achieve this with Paillier. You can try ElGamal (https://github.com/bazzilic/ElGamalExt), which supports multiplication but doesn't support addition, or you can try SEAL (https://www.microsoft.com/en-us/research/project/simple-encrypted-arithmetic-library/), which provides fully homomorphic encryption.

If you are okay to reveal `b`, then you can either do `a + a + ... + a`, adding them together `b` times, ot you can do a "multiply by plaintext constant" trick: https://en.wikipedia.org/wiki/Paillier_cryptosystem#Homomorphic_properties
